@WebApi_HostAddress = http://localhost:5077

GET {{WebApi_HostAddress}}/api/v1/drivers
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=White
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=Walter
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/cars
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/journeys
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/journeys/1fa04c0e-32c5-4226-b444-32a3a0e54870
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/v1/journeys/
Content-Type: application/json

{
  "Origin": "Berlin",
  "Destination": "Paris",
  "DepartureTime": "2023-11-28T16:36:35.911Z",
  "DriverId": 5,
  "CarId": 4
}

###

POST {{WebApi_HostAddress}}/api/v1/journeys/1fa04c0e-32c5-4226-b444-32a3a0e54870/participants
Content-Type: application/json

{
  "FirstName": "Johny",
  "LastName": "Walker",
  
  "Phone": "123456789"
}

###