@WebApi_HostAddress = http://localhost:5077

GET {{WebApi_HostAddress}}/api/v1/drivers
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=White
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=Walter
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/cars
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/journeys
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/journeys/6bf75729-2d2f-4c73-b0bf-f67e7b600fda
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/v1/journeys/
Content-Type: application/json

{
  "Origin": "London",
  "Destination": "Dublin",
  "DepartureTime": "2023-11-30T16:36:35.911Z",
  "DriverId": 7,
  "CarId": 6
}

###

POST {{WebApi_HostAddress}}/api/v1/journeys/6bf75729-2d2f-4c73-b0bf-f67e7b600fda/participants
Content-Type: application/json

{
  "FirstName": "Johny",
  "LastName": "Walker",
  
  "Phone": "123456789"
}

###