@WebApi_HostAddress = http://localhost:5077

GET {{WebApi_HostAddress}}/api/v1/drivers
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=White
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/drivers?name=Walter
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/cars
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/journeys
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/v1/journeys/
Content-Type: application/json

{
  "Origin": "London",
  "Destination": "Birmingham",
  "DepartureTime": "2023-11-23T16:36:35.911Z",
  "DriverId": 1,
  "CarId": 2
}

###

@JourneyId = 1fa04c0e-32c5-4226-b444-32a3a0e54870
POST {{WebApi_HostAddress}}/api/v1/journeys/{{JourneyId}}/participants
Content-Type: application/json

{
  "FirstName": "Jack",
  "LastName": "Daniels",
  "Email": "example@example.com"
  
}

###